name: PlatformIO CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # allow manually calling the action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install PlatformIO
        run: pip install platformio==6.1.19
      - name: Install PlatformIO Libs
        run: pio pkg install
      - name: Use example config
        run: cp src/config_example.h src/config.h
      - name: Run PlatformIO Tests
        # empty target to prevent upload
        run: pio test -e native
      - name: Run PlatformIO
        # empty target to prevent upload
        run: pio run -t ''
