name: PlatformIO CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call: # allow calling from other workflows
  workflow_dispatch: # allow manually calling the action

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install PlatformIO
        run: pip install platformio==6.1.19
      - name: Install PlatformIO Libs
        run: pio pkg install
      - name: Run PlatformIO Tests
        run: pio test -e native

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [inkplate10, inkplate10v2]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install PlatformIO
        run: pip install platformio==6.1.19
      - name: Install PlatformIO Libs
        run: pio pkg install
      - name: Build ${{ matrix.environment }}
        run: pio run -e ${{ matrix.environment }} -t ''
      - name: Rename firmware
        run: cp .pio/build/${{ matrix.environment }}/firmware.bin .pio/build/${{ matrix.environment }}/homeplate-${{ matrix.environment }}.bin
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.environment }}
          path: .pio/build/${{ matrix.environment }}/homeplate-${{ matrix.environment }}.bin
